'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path'),vm=require('vm');
const W=require('../client/bitmap-workflow'),C=require('../client/bitmap-core'),sharp=require('sharp');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sci-workflow-'));let count=0;
async function test(name,fn){await fn();console.log('PASS '+name);count++;}
(async()=>{
await test('Fiji Merge Channels color presets are the ImageJ seven',()=>{const p=W.channelColorPresets();assert.equal(p.length,7);assert.deepEqual(p.map(x=>x.id),['red','green','blue','gray','cyan','magenta','yellow']);assert.deepEqual(p.map(x=>x.hex),['#ff0000','#00ff00','#0000ff','#ffffff','#00ffff','#ff00ff','#ffff00']);});
await test('Magenta/green preserves blue additively and leaves alpha untouched',()=>{let cs=W.channelsDefault();cs.enabled=true;cs.components[0].color='#ff00ff';const a=new Uint8ClampedArray([100,80,40,255,0,0,90,128]);W.mapChannels(a,cs,'merged');assert.deepEqual([...a],[100,80,140,255,0,0,90,128]);});
await test('Keep-channel zeros hidden planes without Enable recoloring',()=>{let cs=W.channelsDefault();cs.enabled=false;cs.components[2].visible=false;const a=new Uint8ClampedArray([10,20,30,255]);W.mapChannels(a,cs,'merged');assert.deepEqual([...a],[10,20,0,255]);});
await test('Keep two channels (R+G) leaves B at zero; single keep extracts that plane',()=>{let cs=W.keepMask(W.channelsDefault().components,[true,true,false]);assert.equal(W.visibleCount(cs),2);let a=new Uint8ClampedArray([40,50,60,255]);W.mapChannels(a,cs);assert.deepEqual([...a],[40,50,0,255]);cs=W.keepMask(W.channelsDefault().components,[false,false,true]);a=new Uint8ClampedArray([40,50,60,255]);W.mapChannels(a,cs);assert.deepEqual([...a],[0,0,60,255]);a=new Uint8ClampedArray([40,50,60,255]);W.mapChannels(a,cs,'blue');assert.deepEqual([...a],[60,60,60,255]);});
await test('Per-component levels, visibility, clipping and solo grayscale',()=>{let cs=W.channelsDefault();cs.enabled=true;cs.components[0].low=20;cs.components[0].high=120;cs.components[1].visible=false;let a=new Uint8ClampedArray([70,100,40,255]);W.mapChannels(a,cs);assert.deepEqual([...a],[128,0,40,255]);a=new Uint8ClampedArray([70,100,40,255]);W.mapChannels(a,cs,'blue');assert.deepEqual([...a],[40,40,40,255]);cs.components[0].color='#ff00ff';a=new Uint8ClampedArray([255,100,255,255]);W.mapChannels(a,cs);assert.equal(a[2],255);});
await test('Per-channel Low/High apply without Enable recoloring (0.9.0)',()=>{
  let cs=W.channelsDefault();assert.equal(W.levelsTouched(cs),false);
  cs.components[0].low=50;cs.components[0].high=150;cs.components[2].low=10;cs.components[2].high=210;
  assert.equal(W.levelsTouched(cs),true);assert.equal(cs.enabled,false);
  let a=new Uint8ClampedArray([100,80,110,255]);W.mapChannels(a,cs,'merged');
  // R:(100-50)*255/100=127.5→127or128; G identity 80; B:(110-10)*255/200=127.5
  assert.equal(a[0],128);assert.equal(a[1],80);assert.equal(a[2],128);assert.equal(a[3],255);
  // Default levels + all visible → early return (unchanged)
  cs=W.channelsDefault();a=new Uint8ClampedArray([10,20,30,255]);W.mapChannels(a,cs);assert.deepEqual([...a],[10,20,30,255]);
});
await test('mapChannels clips below Low and saturates above High per plane',()=>{
  let cs=W.channelsDefault();cs.components[1].low=40;cs.components[1].high=140;
  let a=new Uint8ClampedArray([0,20,255,255,0,140,0,255,0,90,0,255]);
  W.mapChannels(a,cs);
  assert.equal(a[1],0); // 20 < low → 0
  assert.equal(a[5],255); // at high → 255
  assert.equal(a[9],128); // (90-40)*255/100 = 127.5 → 128
});
await test('Preset sanitization excludes paths/geometry/view; invalid inputs fail',()=>{const r=W.recipe({cropLeft:42,path:'/secret',channelView:'red'});assert(!('cropLeft' in r));assert(!('path' in r));assert(!('channelView' in r));assert.throws(()=>W.recipe({toneHigh:0}));assert.throws(()=>W.recipe({brightness:'x'}));let cs=W.channelsDefault();cs.components[2].high=0;assert.throws(()=>W.recipe({channels:cs}));assert.throws(()=>W.parsePresets('{"schema":"other"}'));assert.throws(()=>W.parsePresets(JSON.stringify({schema:'sci-bitmap-presets',version:1,presets:Array(101).fill({name:'A',recipe:{}})})));});
await test('Preset export/import round trip preserves exact RGB recipe',()=>{let cs=W.channelsDefault();cs.enabled=true;cs.components[0].color='#ff00ff';cs.components[2].low=9;let p=[{name:'荧光条件 A',recipe:W.recipe({brightness:12,channels:cs})}];assert.deepEqual(W.parsePresets(JSON.stringify({schema:'sci-bitmap-presets',version:1,presets:p})),p);});
await test('Unsupported depth, stacks, color model and orientation rejected before processing',()=>{const m={width:10,height:8,bitsPerSample:8,photometric:2,samplesPerPixel:3};assert.equal(W.profile(m).kind,'RGB8');for(const extra of [{bitsPerSample:16},{bitsPerSample:32},{hasMoreImages:true},{photometric:5},{orientation:6}])assert.throws(()=>W.profile({...m,...extra}));assert.equal(W.profile({width:10,height:8,bitsPerSample:8,samplesPerPixel:3,colorKind:'RGB',orientation:6}).kind,'RGB8');assert.equal(W.profile({width:10,height:8,bitsPerSample:8,samplesPerPixel:3,colorKind:'GRAY',orientation:8}).kind,'GRAY8');let r=W.recipe({});r.channels.enabled=true;assert.throws(()=>W.compatible(r,{kind:'GRAY8'}));});
await test('TIFF roundtrip plus independent libvips pixel and DPI validation',async()=>{const im={width:3,height:2,data:new Uint8ClampedArray([100,80,140,255,0,0,80,255,255,0,255,255,0,255,0,255,20,40,60,255,0,0,0,255])};const b=W.encodeTiff(im,450,Buffer),f=path.join(dir,'rgb.tif');fs.writeFileSync(f,b);const decoded=W.decodeTiff(b);assert.deepEqual([...decoded.data],[...im.data]);const meta=C.readMetadata(fs,f,Buffer);assert.equal(W.profile(meta).kind,'RGB8');const independent=await sharp(b).raw().toBuffer({resolveWithObject:true});assert.equal(independent.info.channels,4);assert.deepEqual([...independent.data],[...im.data]);assert.equal((await sharp(b).metadata()).density,450);});
await test('Malformed and truncated TIFF does not yield pixels',()=>{let b=W.encodeTiff({width:1,height:1,data:new Uint8ClampedArray([1,2,3,255])},300,Buffer);assert.throws(()=>W.decodeTiff(b.subarray(0,b.length-1)));b.writeUInt32LE(0xfffffff0,4);assert.throws(()=>W.decodeTiff(b));});
await test('Real compressed TIFF metadata classifies RGB8, gray8, and gray16',async()=>{for(const kind of ['rgb','gray','gray16']){let f=path.join(dir,kind+'.tif');let image=sharp({create:{width:10,height:8,channels:3,background:'#804020'}});if(kind!=='rgb')image=image.greyscale().toColourspace('b-w');if(kind==='gray16')image=image.toColourspace('grey16');await image.tiff({compression:'lzw'}).toFile(f);const meta=C.readMetadata(fs,f,Buffer);if(kind==='gray16'){assert.throws(()=>W.profile(meta));}else assert.equal(W.profile(meta).kind,kind==='rgb'?'RGB8':'GRAY8');assert.throws(()=>W.decodeTiff(fs.readFileSync(f)));}});
await test('Batch host deduplicates targets and does not follow changed selection',()=>{const doc={name:'test.ai',fullName:{fsName:'/test.ai'},selection:[]};let writes=[];function item(id){return {typename:'PlacedItem',uuid:id,name:id,embedded:false,file:{fsName:'/same.tif',exists:true,length:12},width:10,height:10,position:[0,10],geometricBounds:[0,10,10,0],matrix:{mValueA:1,mValueB:0,mValueC:0,mValueD:1,mValueTX:0,mValueTY:0},relink(f){writes.push(id);this.file=f;},remove(){},move(){},translate(){},selected:false};}doc.placedItems={add(){const pool=[a,b,other]; const t=pool.find(x=>x.__sciPlaceTarget)||doc.selection[0]||item('placed'); return {set file(f){writes.push(t.uuid);t.file=f;},get file(){return t.file;},get typename(){return 'PlacedItem';},get uuid(){return t.uuid;},get name(){return t.name;},get embedded(){return false;},get width(){return t.width;},set width(v){t.width=v;},get height(){return t.height;},set height(v){t.height=v;},get position(){return t.position;},set position(v){t.position=v;},get geometricBounds(){return t.geometricBounds;},get matrix(){return t.matrix;},move(){},remove(){},translate(){},set selected(v){t.selected=v;}};}};let a=item('a'),b=item('b'),other=item('other');doc.selection=[a,b,a];let ctx={app:{documents:[doc],activeDocument:doc,redraw(){},getIdentityMatrix(){return {mValueA:1,mValueB:0,mValueC:0,mValueD:1,mValueTX:0,mValueTY:0};}},File:function(p){this.fsName=p;this.exists=true;this.length=12;},ElementPlacement:{PLACEBEFORE:0}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../jsx/bitmap.jsx'),'utf8'),ctx);let review=JSON.parse(ctx.captureBitmapBatch());assert.equal(review.items.length,2);doc.selection=[other];assert(JSON.parse(ctx.replaceBatchBitmap(review.token,0,'/out.tif')).ok);assert.deepEqual(writes,['a']);b.matrix.mValueTX=10;assert(!JSON.parse(ctx.replaceBatchBitmap(review.token,1,'/out.tif')).ok);assert.deepEqual(writes,['a']);ctx.releaseBitmapBatch(review.token);assert(!JSON.parse(ctx.replaceBatchBitmap(review.token,0,'/out.tif')).ok);});
console.log('\n'+count+' workflow checks passed.');fs.rmSync(dir,{recursive:true,force:true});
})().catch(e=>{console.error(e);fs.rmSync(dir,{recursive:true,force:true});process.exit(1);});
